### ISSUE TITLE
当visible 的属性值抽象到state里面时，总是报warning

### ISSUE THREAD

**Issue by onlyLiru** [reactnativecn/react-native.cn#104]
调用modal组件：
<Modal
	          animationType={"slide"}
	          transparent={false}
	          visible={ this.state.modalVisible }
	          >
抽象visible属性：
this.state={
			modalVisible:false,
		}
控制台打印出来的warning：

Warning: Failed prop type: Invalid prop `visible` of type `object` supplied to `Modal`, expected `boolean`.
    in Modal (created by CommentList)
    in CommentList (created by VideoDetail)
    in RCTView (created by View)
    in View (created by VideoDetail)
    in VideoDetail (created by Navigator)
    in RCTView (created by View)
    in View (created by Navigator)
    in RCTView (created by View)
    in View (created by Navigator)
    in RCTView (created by View)
    in View (created by Navigator)
    in Navigator (created by LiruIos)
    in StaticContainer (created by TabBarItemIOS)
    in RCTTabBarItem (created by TabBarItemIOS)
    in TabBarItemIOS (created by TabBarItemIOS)
    in TabBarItemIOS (created by LiruIos)
    in RCTTabBar (created by TabBarIOS)
    in TabBarIOS (created by LiruIos)
    in LiruIos
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

请问原因？如何解决？

**Comment by sunnylqm** [comment]
贴完整代码吧
