### ISSUE TITLE
内容部分为什么不全部使用markdown，而是直接使用了html？？？

### ISSUE THREAD

**Issue by futurechallenger** [reactnativecn/react-native.cn#110]
我想帮你们翻译一下关于flex布局的部分，发现在flex布局的部分居然都是html的网页标签。
太不翻译友好了！！！

**Comment by sunnylqm** [comment]
从一开始就没有使用官方的文档代码，所以导致目前只能这样尴尬处理。。。
而且如果使用官方的文档代码，可能更尴尬，因为大部分文档都直接写在js源码中
