### ISSUE TITLE
网站显示与github上不一致

### ISSUE THREAD

**Issue by gzponline** [reactnativecn/react-native.cn#121]
![image](https://cloud.githubusercontent.com/assets/12186221/24963008/0d73f542-1fd0-11e7-9428-75de16090079.png)
souce ～/.bash_profile 不是souce ./bash_profile

**Comment by sunnylqm** [comment]
你看的是哪个版本？老版本可能有错

**Comment by gzponline** [comment]
https://reactnative.cn/docs/0.43/getting-started.html
这个应该是最新版吧， google搜索最佳匹配

**Comment by sunnylqm** [comment]
看到了，是在linux部分，感谢指出
