### ISSUE TITLE
[嵌入到现有原生应用]这里说的根目录有歧义

### ISSUE THREAD

**Issue by sharh** [reactnativecn/react-native.cn#152]
`根目录`不是项目目录，是项目目录的上一层目录，as的indexing已经导致我卡死了好几次了。看了react-native init 产生的项目目录结构才明白过来！！！

这个歧义一旦as开始index就会卡死。建议改下，防止新手卡死！！！

**Comment by sunnylqm** [comment]
“项目目录的上一层目录”就没有歧义了？“项目目录”的定义又是什么？

**Comment by sharh** [comment]
项目目录就是新建的项目目录啊，这种应该没歧义吧。总比你写的根目录应该好理解啊。或者你可以搞个目录示例会不会好点？

**Comment by sunnylqm** [comment]
我只能说嵌入原生之前应该先起码跑个纯RN的helloworld
任何树的根都是确定的吧？所以我不认为`根目录`存在任何歧义，而且这并不是我“写的”，官方就是称root directory/folder

**Comment by sharh** [comment]
好吧，可能是我理解有问题
