### ISSUE TITLE
能否移除reactnative网站链接后面的#content

### ISSUE THREAD

**Issue by EzioKissshot** [reactnativecn/react-native.cn#163]
目录链接后面都有#content，每次点击都会跳到页面最下方，一片空白，需要上滚才能看到内容
使用的是Chrome 版本 59.0.3071.115

**Comment by sunnylqm** [comment]
可以看下chrome控制台有什么报错吗

**Comment by EzioKissshot** [comment]
随便点了几下，有以下错误，希望能有帮助就好了 @sunnylqm 

Mixed Content: The page at 'https://reactnative.cn/docs/0.44/progressbarandroid.html#content' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://zhannei.baidu.com/cse/site'. This endpoint should be made available over a secure connection.

===

favicon.ico:1 GET https://reactnative.cn/favicon.ico 404 ()

===

loadResource.js:39 GET https://reactnative.cn/proxy/openapi.youku.com/v2/videos/by_user.json?user_name=react-native&client_id=3f4eca228da38d9e&count=100 504 ()
(anonymous) @ loadResource.js:39
r @ runtime.js:65
(anonymous) @ runtime.js:303
e.(anonymous function) @ runtime.js:117
r @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:35
t @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
(anonymous) @ index.4184b95….js:2317
o @ loadResource.js:62
(anonymous) @ ViewRecords.js:31
r @ runtime.js:65
(anonymous) @ runtime.js:303
e.(anonymous function) @ runtime.js:117
r @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:35
t @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
value @ NavBar.js:83
e.notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:209
perform @ Transaction.js:156
s @ ReactMount.js:126
perform @ Transaction.js:143
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
o @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:319
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
a @ index.web.js:40
(anonymous) @ index.web.js:51
t @ bootstrap 4184b95…:19
(anonymous) @ bootstrap 4184b95…:39
(anonymous) @ bootstrap 4184b95…:39

===

ViewRecords.js:34 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at ViewRecords.js:34
    at <anonymous>
(anonymous) @ ViewRecords.js:34

**Comment by sunnylqm** [comment]
content的目的本身其实就是为了页面能自动滚回顶部
你贴的这几个问题也没看出关联性，我先屏蔽掉试试
