### ISSUE TITLE
运行失败 -empty error

### ISSUE THREAD

**Issue by zelinDavid** [reactnativecn/react-native.cn#164]
由于0.45版本发布,用之前的 react-native init (项目名称) 会运行失败,改为 react-native init (项目名称) --version 0.44.0 就可以,我花了七个多小时才解决这个问题,希望及时更新下,让其他同学少踩坑.

具体如下:  
http://bbs.reactnative.cn/topic/4007/%E5%88%9B%E5%BB%BArn%E9%A1%B9%E7%9B%AErun-ios%E5%90%8E%E6%8A%A5%E9%94%99%E4%BA%86-%E5%8F%AF%E8%83%BD%E6%98%AF%E7%89%88%E6%9C%AC%E4%BE%9D%E8%B5%96%E7%9A%84%E9%97%AE%E9%A2%98-%E4%BD%86%E5%B0%B1%E6%98%AF%E4%B8%8D%E7%9F%A5%E9%81%93%E5%9C%A8%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3/2

**Comment by sunnylqm** [comment]
![tim 20170710084818](https://user-images.githubusercontent.com/615282/27999183-9252c718-654c-11e7-8058-292938d3c1e7.png)

**Comment by sunnylqm** [comment]
你如果认真看文档或者看论坛的帖子，七分钟都不用
