### ISSUE TITLE
希望能把菜单译文的原文显示出来方便大家搜索

### ISSUE THREAD

**Issue by hookbin** [reactnativecn/react-native.cn#182]

**Comment by sunnylqm** [comment]
什么菜单

**Comment by hookbin** [comment]
http://reactnative.cn/docs/0.48/getting-started.html#content
左侧菜单栏额外展示原文或关键词，例如：
```
- 如何使用滚动视图（Using a ScrollView 或 ScrollView）
- 如何使用控件列表（Using List Views 或 ListViews）
- 网络（Networking）
```
还有请把Components翻译完全，别烂尾啊~~~谢谢

**Comment by sunnylqm** [comment]
我们保留了组件和api原文，教程没这个必要吧。

欢迎参与翻译。

**Comment by hookbin** [comment]
有必要的!!!转职而来在其他语言中的通用词用来检索可以更针对的解决问题

**Comment by sunnylqm** [comment]
教程里没有任何称得上对解决问题有帮助的信息

你该搜索的只有一个地方，那就是官方的issues
