### ISSUE TITLE
原生组件调用失败

### ISSUE THREAD

**Issue by jiajun1203** [reactnativecn/react-native.cn#234]
使用指南(IOS)-原生组件

XCode中配置好后，RN中获取原生View
module.exports = requireNativeComponent('RNTMap', null);

RNTMap是从哪里来的？  一直无法找到。 现在的项目和文档中的一样，也是因为无法找到标识无法获取到原生View。

**Comment by sunnylqm** [comment]
requireNativeComponent 自动把'RNTMap'解析为'RNTMapManager'

**Comment by jiajun1203** [comment]
Thanks，改好了！




发自网易邮箱大师
在2018年04月25日 15:05，Sunny Luo 写道：

Closed #234.
