### ISSUE TITLE
关于版本的问题

### ISSUE THREAD

**Issue by chuyinweilai** [reactnativecn/react-native.cn#239]
我最近看英文官网，发现官方推荐的是create-react-native-app脚手架加expo调试，中文网是react-native init脚手架和Genymotion调试，这个差异是出于什么考虑吗？

**Comment by sunnylqm** [comment]
沙盒环境大量依赖于国外网络环境，也不能直接发布应用，只是用于学习、演示、试验等目的。因此不建议国内用户使用。
