### ISSUE TITLE
0.39版的android打包apk 还没有翻译呀

### ISSUE THREAD

**Issue by Yangzhedi** [reactnativecn/react-native.cn#70]
react-native.cn/docs/docs/0.39/signed-apk-android.md

是需要认领翻译吗？ 还是疏忽没传中文版？

**Comment by sunnylqm** [comment]
是还没翻译，我争取今天补上吧

**Comment by Yangzhedi** [comment]
如果 你时间不够的话，开个issue  让爱好者自由认领翻译就可以啊，你们负责校对

**Comment by sunnylqm** [comment]
从来都是开放PR的啊，然而并没有人提交什么（少数人挑错字倒是有）

**Comment by Yangzhedi** [comment]
好吧好吧 下次我争取提交点什么~~

**Comment by sunnylqm** [comment]
已提交
