### ISSUE TITLE
希望你们不要再放东风耀的视频推广了，进了他们vip，就是一骗子，专门骗人去搞什么一点公益

### ISSUE THREAD

**Issue by dengyhgit** [reactnativecn/react-native.cn#79]
希望你们不要再放东风耀的视频推广了，进了他们vip，就是一骗子，专门骗人去搞什么一点公益，还用首先绑架，说是不是信息不过他的为人，他的为人值不了半毛钱，你们是收了广告费还什么什么原因，但希望让更多 的人上骗了，谢谢你们

**Comment by sunnylqm** [comment]
感谢反馈。我们已移除广告。
