### ISSUE TITLE
嵌入原生应用中的node-modules路径有问题吧？

### ISSUE THREAD

**Issue by kebenxiaoming** [reactnativecn/react-native.cn#81]
http://reactnative.cn/docs/0.40/integration-with-existing-apps.html#content

这里面的
allprojects {
    repositories {
        ...
        maven {
            // All of React Native (JS, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
    ...
}
其中的uri  "$rootDir/node_modules/react-native/android"这样吧?这样才好用

**Comment by sunnylqm** [comment]
表示这里和官方文档一致，一直也没有接到类似你这样的反馈。

**Comment by kebenxiaoming** [comment]
@sunnylqm 不知道啊，你用过哪个版本的 compile "com.facebook.react:react-native:+" ?

在我用目前文档中的url "$rootDir/../node_modules/react-native/android"时，很奇怪，不好用...

我发现我改成uri "$rootDir/node_modules/react-native/android"之后可能android的react-native类库版本也变化了，import com.facebook.react.common.LifecycleState;的位置变了。然后mReactInstanceManager的生命周期方法也变化了。不过好用了，你试一下

**Comment by sunnylqm** [comment]
首先得确定你的项目目录结构是否和官方文档一致了。还有一个问题就是，即便这个路径不匹配，实际也不会报错，而是会自动去下载中央maven库的0.20版本的react native。你也可以检查下你是不是这个版本。

**Comment by kebenxiaoming** [comment]
@sunnylqm 想起来了，应该是目录结构不一致，我没有加别的module模块，只是一个新建的工程，如果是有别的模块gradle配置文件位置会变化。这边算记录下吧，如果是个简单的新建的工程，可以试试改改uri "$rootDir/node_modules/react-native/android"。
谢了，那我关了
