### ISSUE TITLE
‘refs’ recommend in TouchableHighlight 

### ISSUE THREAD

**Issue by l770826421** [reactnativecn/react-native.cn#82]
1. When I leaning ref，find  use ref in TouchaleHighlight ,example:
<TouchableHighlight
        style={{margin: 10, marginTop: 10}}
        onPress={this._onPressMeasureTouch.bind(this)} >
         <Text ref='touchable' >4.TouchableHighlight获取视图在屏幕上的位置和尺寸</Text>
</TouchableHighlight>
in _onPressMeasureTouch,can't use this.refs.touchble,beacuse this.refs.touchble is undefined。

2. Android timer in the debug state will be stuck in the UI thread release when the normal trouble also remember to submit。

**Comment by sunnylqm** [comment]
这类问题请去论坛讨论  <http://bbs.reactnative.cn>
