### ISSUE TITLE
打包apk之后在app中执行一些操作时会闪退

### ISSUE THREAD

**Issue by xjbw** [reactnativecn/react-native.cn#83]
如题所述，之前在开发APP的时候都是在真机上进行调试，初步测试完成后打包了一个APK想让朋友们安装测测bug，但是打包出来的APK安装后，在APP的登录界面点击登录后会闪退。但调试的时候不会，而且用调试那台手机安装打包出的APP也会在登录的时候闪退。之前打包过不会闪退，这两天加了些权限和功能再打包就不行了。

**Comment by sunnylqm** [comment]
这类问题请去论坛讨论
